Обработаны основные запросы от клиента на сервер
MoodyAir/TP-QG-H-TRY pull request #7
Opened 2021-05-06 22:56 UTC by SERPSLAYER18

- Вопрос по сложности и теме
- Есть ли пользователь с таким именем и паролем
- Правильный ответ по id вопроса

2021-05-07 10:12 UTC, MoodyAir commented on src/main/java/com/questgame/mapper/UserMapper.java
> +        if(user == null)
Эту проверку наверное лучше убрать, у меня на уровне service есть проверка на нулевое значение

2021-05-09 21:14 UTC, VeronikaYastr requested changes

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/controller/SocketController.java
> +
лишняя пустая строка

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/controller/SocketController.java
> +    switch (messageType){
форматирование явно немного съехало. Ctrl+Alt+L

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/dto/ConformationDto.java
> +public class ConformationDto {
мб Conf**i**rmation?

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/dto/CorrectAnswerDto.java
> +package com.questgame.dto;
Может лучше типы данных которые именно в сообщениях используются в какой-то отдельный пакет вынести? или добавить им какой-то кусочек имени (типа CorrectAnswer**Message**) ?

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/dto/MessageType.java
> +    question,
У енама обычно ВОТ_ТАКИМ_СПОСОБОМ_ПЕРЕМЕННЫЕ_НАЗЫВАЮТСЯ)

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/mapper/UserMapper.java
> +        if(user == null)
Я бы не убирала, потому что метод могут вызвать откуда угодно потенциально. лучше не надеяться на то что где-то там есть проверка

2021-05-09 21:14 UTC, VeronikaYastr commented on src/main/java/com/questgame/controller/SocketController.java
> +    public Object replyMessage(String  JSONString) {
А зачем вам вообще Gson когда вы используете stomp и там по идее просто класс указываешь и он в json конвертируется?

2021-05-12 18:40 UTC, merged